package com.tadams.pcg.tomb.model;

/**
 * Created by tadams on 12/23/15.
 */
public enum Footrinsics {
    RESISTANCE, // many
    SEARCHING,
    REGENERATION,
    INVISIBLE,
    SEE_INVISIBLE,
    TELEPORT,
    TELEPORT_CONTROL,
    POLYMORPH,
    POLYMORPH_CONTROL,
    LEVITATION,
    STEALTH,
    AGGRAVATE,
    CONFLICT,
    PROTECTION,
    SHAPECHANGER_PROTECTION,
    WARNING,
    HUNGER,
    TELEPATHY,
    SPEED,
    FOOD_APPRAISAL,
    UNBREATHING,
    WATER_BREATHING,
    JUMPING,
    INFRAVISION,
    ADORNMENT,
    REFLECTION,
    LIFE_SAVING,
    PHASING,
    FUMBLING,
    WATER_WALKING,
    DISPLACEMENT
}
